/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAside: typeof import('./src/components/app/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/app/AppHeader.vue')['default']
    AppNav: typeof import('./src/components/app/AppNav.vue')['default']
    AppNotification: typeof import('./src/components/app/AppNotification.vue')['default']
    AppOverlay: typeof import('./src/components/app/AppOverlay.vue')['default']
    AppProgress: typeof import('./src/components/app/AppProgress.vue')['default']
    BlockBreadcrumb: typeof import('./src/components/block/breadcrumb/BlockBreadcrumb.vue')['default']
    BlockInfo: typeof import('./src/components/block/info/BlockInfo.vue')['default']
    CardBase: typeof import('./src/components/dashboard/cards/CardBase.vue')['default']
    CardButton: typeof import('./src/components/dashboard/cards/CardButton.vue')['default']
    CardDate: typeof import('./src/components/dashboard/cards/CardDate.vue')['default']
    CardDimmer: typeof import('./src/components/dashboard/cards/CardDimmer.vue')['default']
    CardInfo: typeof import('./src/components/dashboard/cards/CardInfo.vue')['default']
    CardInput: typeof import('./src/components/dashboard/cards/CardInput.vue')['default']
    CardList: typeof import('./src/components/dashboard/cards/CardList.vue')['default']
    CardMain: typeof import('./src/components/card/main/CardMain.vue')['default']
    CardNotification: typeof import('./src/components/card/notification/CardNotification.vue')['default']
    IconRiAddLine: typeof import('~icons/ri/add-line')['default']
    IconRiArrowDropDownLine: typeof import('~icons/ri/arrow-drop-down-line')['default']
    IconRiArrowDropRightLine: typeof import('~icons/ri/arrow-drop-right-line')['default']
    IconRiArrowRightSLine: typeof import('~icons/ri/arrow-right-s-line')['default']
    IconRiArrowUpSLine: typeof import('~icons/ri/arrow-up-s-line')['default']
    IconRiCloseLine: typeof import('~icons/ri/close-line')['default']
    IconRiFolder6Line: typeof import('~icons/ri/folder6-line')['default']
    IconRiListCheck: typeof import('~icons/ri/list-check')['default']
    IconRiLogoutBoxLine: typeof import('~icons/ri/logout-box-line')['default']
    IconRiMenuLine: typeof import('~icons/ri/menu-line')['default']
    IconRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IconRiMoreLine: typeof import('~icons/ri/more-line')['default']
    IconRiNotificationLine: typeof import('~icons/ri/notification-line')['default']
    IconRiShutDownLine: typeof import('~icons/ri/shut-down-line')['default']
    IconRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IconRiTimeLine: typeof import('~icons/ri/time-line')['default']
    ItemEdit: typeof import('./src/components/dashboard/edit/ItemEdit.vue')['default']
    ItemOptions: typeof import('./src/components/dashboard/edit/ItemOptions.vue')['default']
    VAccordion: typeof import('./src/components/ui/accordion/VAccordion.vue')['default']
    VAccordionItem: typeof import('./src/components/ui/accordion/VAccordionItem.vue')['default']
    VAutocomplete: typeof import('./src/components/ui/autocomplete/VAutocomplete.vue')['default']
    VButton: typeof import('./src/components/ui/button/VButton.vue')['default']
    VCheckbox: typeof import('./src/components/ui/checkbox/VCheckbox.vue')['default']
    VDialog: typeof import('./src/components/ui/dialog/VDialog.vue')['default']
    VDragDrop: typeof import('./src/components/ui/drag-drop/VDragDrop.vue')['default']
    VDropdown: typeof import('./src/components/ui/dropdown/VDropdown.vue')['default']
    VExpansion: typeof import('./src/components/ui/expansion/VExpansion.vue')['default']
    VFile: typeof import('./src/components/ui/file/VFile.vue')['default']
    VFunc: typeof import('./src/components/ui/func/VFunc.vue')['default']
    VIconLogo: typeof import('./src/components/ui/icon/VIconLogo.vue')['default']
    VIconLogoMini: typeof import('./src/components/ui/icon/VIconLogoMini.vue')['default']
    VList: typeof import('./src/components/ui/list/VList.vue')['default']
    VListObject: typeof import('./src/components/ui/list/VListObject.vue')['default']
    VLoader: typeof import('./src/components/ui/loader/VLoader.vue')['default']
    VPopup: typeof import('./src/components/ui/dialog/VPopup.vue')['default']
    VSelect: typeof import('./src/components/ui/select/VSelect.vue')['default']
    VTable: typeof import('./src/components/ui/table/VTable.vue')['default']
    VTabs: typeof import('./src/components/ui/tabs/VTabs.vue')['default']
    VTextField: typeof import('./src/components/ui/text-field/VTextField.vue')['default']
    VTextWrapper: typeof import('./src/components/ui/text-wrapper/VTextWrapper.vue')['default']
    VTooltip: typeof import('./src/components/ui/tooltip/VTooltip.vue')['default']
    VWifiIcon: typeof import('./src/components/ui/wifiIcon/VWifiIcon.vue')['default']
  }
}
